root: true
parser: babel-eslint
settings:
  import/resolver: webpack

parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    jsx: true
    destructuring: true
    spread: true

env:
  browser: true

plugins:
  - react

extends: airbnb

rules:
  no-console: warn
  no-alert: off
  no-unused-vars: warn
  semi: [warn, never]
  new-cap: off
  quotes: [warn, single]
  react/prop-types: off
  react/prefer-stateless-function: off
  no-else-return: off
  no-use-before-define: off
  no-mixed-operators: off
  no-shadow: warn
  jsx-a11y/href-no-hash: off
  prefer-template: warn
  react/no-array-index-key: off
  react/forbid-prop-types: off
  jsx-a11y/no-static-element-interactions: off
  jsx-a11y/no-noninteractive-element-interactions: off
  no-restricted-syntax: off
  react/no-did-mount-set-state: off
  react/no-did-update-set-state: off
  react/require-default-props: off
