cluster:
  - clusterType: DBSCAN
    args:
      - name: distThreshold
        type: double
        defaultValue: 5
        unit: 米
        desc: 最大距离
      - name: timeThreshold
        type: int
        defaultValue: 300
        unit: 秒
        desc: 最大时间
      - name: minPts
        type: int
        defaultValue: 2
        unit: 个
        desc: 最少点个数
      - name: adaptive
        type: boolean
        defaultValue: false
        desc: 自适应调整时间
      - name: distanceType
        type: enum
        defaultValue: Euclidean
        values: [Euclidean, MIWD]
        desc: 距离尺度

  - clusterType: Heuristic
    args:
      - name: personSpeed
        type: double
        defaultValue: 1.8
        unit: 米/秒
        desc: 最大移动速度
      - name: distThreshold
        type: double
        defaultValue: 10
        unit: 米
        desc: 最大距离
      - name: timeThreshold
        type: int
        defaultValue: 300
        unit: 秒
        desc: 最大时间

floorFixer:
  - fixerType: ByRule
    args:
      - name: sectionSplitTime
        type: int
        defaultValue: 1200
        unit: 秒
        desc: 区间分割时间

  - fixerType: ByFilter
    args:
      - name: windowSize
        type: oddInt
        defaultValue: 3
        desc: 中值滤波器窗口大小
      - name: sectionSplitTime
        type: int
        defaultValue: 1200
        unit: 秒
        desc: 区间分割时间
