export const DELETE_MAC_ITEM = 'DELETE_MAC_ITEM'
export const EDIT_MAC_ITEM = 'EDIT_MAC_ITEM'
export const ADD_MAC_ITEM = 'ADD_MAC_ITEM'
export const UPDATE_MAC_ITEMS = 'UPDATE_MAC_ITEMS'

export const UPDATE_LOCATION_ITEMS = 'UPDATE_LOCATION_ITEMS'
